const PREVIEW_GIFTS_SPREADSHEET = '1PPo2GKYjaz0FvNE9eBCooE98MbphLvxCxjJavI5jjJM'
const GIFTS_SPREADSHEET = '1PPo2GKYjaz0FvNE9eBCooE98MbphLvxCxjJavI5jjJM'

export const spreadSheetId =
  process.env.NODE_ENV === 'production' ? GIFTS_SPREADSHEET : PREVIEW_GIFTS_SPREADSHEET
